### ISSUE TITLE
how do I create my own insitu.matrix in DistMap and what files are needed ?

### ISSUE THREAD

**Issue by VBRay** [rajewsky-lab/distmap#4]

**Comment by nukappa** [comment]
The insitu.matrix is a binary matrix (only 0s and 1s), reflecting real OFF/ON gene expression. For the fly embryo case, it is provided. For other tissues, you'd have to construct it.

**Comment by VBRay** [comment]
you mean i need to construct it for each of different tissue?
But I don't know how construct the insitu.matrix, what data do I need to prepare? there is no example to show how to make it.

**Comment by mschilli87** [comment]
@VBRay 
> you mean i need to construct it for each of different tissue?

@nukappa 
> For the fly embryo case, it is provided. For other tissues, you'd have to construct it.

---
@VBRay 
> But I don't know how construct the insitu.matrix, what data do I need to prepare?

@nukappa 
> The insitu.matrix is a binary matrix (only 0s and 1s), reflecting real OFF/ON gene expression.

---
@VBRay 
> there is no example to show how to make it.

@nukappa 
> For the fly embryo case, it is provided.

**Comment by VBRay** [comment]
For the fly embryo case, is it provided in the supplementary of the published paper and
where is it's position
![1540257668 1](https://user-images.githubusercontent.com/33386972/47328790-006ea800-d6a5-11e8-99c1-c18a281aadad.jpg)
 ?

**Comment by mschilli87** [comment]
@VBRay:
I assume it is provided on [the top level of this very git repository](https://github.com/rajewsky-lab/distmap) with the filename [`insitu_matrix.txt`](https://github.com/rajewsky-lab/distmap/blob/master/insitu_matrix.txt).

In the TOC you copied (without reference!), I'd look at page 8 as it mentiones the 
> Binarization of the BDTNP reference atlas.

or in other words, the convertion of the *in situ* data used to ones and zeroes.

**Comment by VBRay** [comment]
yeah, I know that in the insitu_matrix.txt, genes as columns and positions (bins) as rows. But what does the position mean, a cell or others? Is it similar to a gene expression matrix ?
