### ISSUE TITLE
A  question about distmap

### ISSUE THREAD

**Issue by caiquanyou** [rajewsky-lab/distmap#6]
I have a Problem about Distmap and novosparc; can not understand their difference?could you please help to provide a small example ?

**Comment by nukappa** [comment]
Hi @caiquanyou 
novosparc is a more advanced computational tool for spatial reconstruction, so I'd use directly this one today, unless your organism is the fly embryo. The main difference is that novosparc doesn't require marker genes for the reconstruction.
There is a published paper associated with each tool, it's maybe a good idea to start there.
