### ISSUE TITLE
test.r script runs error

### ISSUE THREAD

**Issue by jlchen5** [rajewsky-lab/distmap#7]
While I was running the test.r 

`source("/mydaten/projects/fly/src/spatial_mapping.R")
load('/mydaten/projects/fly/src/great_mapping/fly_cherries.cleaned_col.Robj')`

but this Repositories did not provide the files?

**Comment by nukappa** [comment]
Hi, indeed we don't provide them but they're not needed, the data is loaded directly from the DGE file.
